# -*- coding: utf-8 -*-
"""CamelCase

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NtLbmnwpouHFuiGV9_m0AvfeYUmatmwq
"""

#include <bits/stdc++.h>

using namespace std;

int camelcase(string s) {

}

int main()
{
    ofstream fout(getenv("OUTPUT_PATH"));

    string s;
    getline(cin, s);

    int result = camelcase(s);

    fout << result << "\n";

    fout.close();

    return 0;
}