# -*- coding: utf-8 -*-
"""leap year

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rahrJ8JBfnHvu0553BxDZAdkBX5xNRDb
"""

#include <iostream>
using namespace std;
int main() {
   int year = 2020;
   if (year % 4 == 0) {
      if (year % 100 == 0) {
         if (year % 400 == 0)
         cout << year << " is a leap year";
         else
         cout << year << " is not a leap year";
      } else
      cout << year << " is a leap year";
   } else
   cout << year << " is not a leap year";
   return 0;
}