# -*- coding: utf-8 -*-
"""Swapping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nko9X5R1JaC_mSkWHH7jR9ys_ILLKrpn
"""

#include <iostream>
using namespace std;

int main()
{
    int a = 5, b = 10, temp;

    cout << "Before swapping." << endl;
    cout << "a = " << a << ", b = " << b << endl;

    temp = a;
    a = b;
    b = temp;

    cout << "\nAfter swapping." << endl;
    cout << "a = " << a << ", b = " << b << endl;

    return 0;
}